########## DECLARE VARIABLES
DECLARE dataset_name STRING DEFAULT @dataset_name;
DECLARE orderline_table STRING DEFAULT @orderline_table;
DECLARE start_date DATE DEFAULT @start_date;
DECLARE markets ARRAY<STRING> DEFAULT @markets;

EXECUTE IMMEDIATE FORMAT("""
  SELECT
      o.MARKET,
      DATE(o.DATETIME_CREATION_ORDERLINE_LOCAL_TIME) AS DATE_KPI,
      o.CLIENT_COUNTRY, o.CLIENT_GMA_CODE, o.CLIENT_GMA_NAME,
      SUM(o.QUANTITY) AS QUANTITY,
      COUNT(DISTINCT o.ORDERLINE_ID) AS ORDERS,
      SUM(o.GMV_LOCAL_CURRENCY) AS GMV_LOCAL_CURRENCY,
      COUNT(DISTINCT o.CLIENT_ID) AS CLIENTS
  FROM `%s.%s` o
  WHERE 1=1
      AND o.ORDERLINE_STATE IN (1,2,3,4,5)
      AND DATE(DATE_CREATION_ORDERLINE_LOCAL_TIME) >= DATE('%s')
      AND o.MARKET IN UNNEST(%s)
  GROUP BY 1,2,3,4,5
  ORDER BY 1,2,3,4,5
""", dataset_name, orderline_table, start_date, FORMAT("ARRAY%s", TO_JSON_STRING(markets)));
